In [1]:
# Dependencies
from splinter import Browser
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
# Setting up chromedriver
executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
url = 'https://www.indeed.com/jobs?q=data+analyst&l=United+States'
browser.visit(url)

In [6]:
counter = 0
html = browser.html
soup = BeautifulSoup(html, 'html.parser')
total_pages_string = soup.find('div', id='searchCountPages').text
total_pages_string = total_pages_string.split()
total_pages = int(total_pages_string[3].replace(",", ""))
print(total_pages)

for x in range(1, 10):
    
    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    print(f'Page: {x}')
    print('-'*80)

    postings = soup.find_all('div', class_='jobsearch-SerpJobCard')

    for posting in postings:
        counter += 1
        
        # Get company name
        try:
            company_name_tag = posting.find('span',class_="company")
            company_name = company_name_tag.find('a').text
        except:
            company_name = posting.find('span',class_="company").text
            
        # Get job title
        job_title = posting.find('h2', class_="title").text

        # Get location
        try:
            job_location = posting.find('div', class_="location").text
        except:
            job_location = posting.find('span', class_="location").text

        # Get salary
        try:
            salary = posting.find('span', class_="salaryText").text
        except:
            salary = "NA"
            
        print(f'Posting #{counter}')  
        print(company_name)
        print(job_title)
        print(job_location)
        print(salary)
        print('-'*40)
    
    try:
        # If the next symbol is an arrow use the below code
#         next_anchor = soup.find('a', {"aria-label": "Next"})
#         next_page_url = next_anchor['href']
#         browser.click_link_by_partial_href(next_page_url)

        # If the next page is "Next" use this code
        browser.click_link_by_partial_text('Next')


        print("********************Success!!********************")
    except:
        print("********************Did not go to next page!!********************")
        break

12014
Page: 1
--------------------------------------------------------------------------------
Posting #1

Sourceability


Business Intelligence Analyst/Data Analyst

Irvine, CA 92618 (Irvine Health and Science Complex area)
NA
----------------------------------------
Posting #2

Private


Data Analyst

St. Louis, MO 63123

$13 an hour
----------------------------------------
Posting #3

The Brixton Group


Sr. Data Analyst

Huntersville, NC 28078

$100,000 - $135,000 a year
----------------------------------------
Posting #4

Confidential


Data Analyst

Santa Ana, CA
NA
----------------------------------------
Posting #5

Bellwether Staffing Solutions


Audit Data Analyst

White Plains, NY

$85,000 - $90,000 a year
----------------------------------------
Posting #6

Oneida Nation Enterprises


Business Analyst - Transformation

Verona, NY 13478

$40,000 - $80,000 a year
----------------------------------------
Posting #7

Comprehensive Health Serv


Data Analyst

Reston, VA 20190
NA
----------------------------------------
Posting #8

Showwcase


Data Analyst Intern

San Francisco, CA

$16 an hour
----------------------------------------
Posting #9

Santanna Energy Services


Junior Data Analyst
new
Austin, TX 78729
NA
----------------------------------------
Posting #10

Verde Natural


Data Analyst

Denver, CO 80216 (Northeast Park Hill area)
NA
----------------------------------------
Posting #11

LabYakk


Data Science Intern
new
San Francisco Bay Area, CA

$19 - $21 an hour
----------------------------------------
Posting #12

Indiana State Department of Health


Epidemiology Data Analyst (Contract)

Indianapolis, IN 46204 (Downtown area)

$21 an hour
----------------------------------------
Posting #13

Cobbs Creek Healthcare


Entry Level Data Analyst - Summer 2020

Newtown Square, PA 19073
NA
----------------------------------------
Posting #14

Entera


Product and Data Analyst

Houston, TX
NA
----------------------------------------
Posting #15

Reynolds and Reynolds


Data Analyst

Houston, TX 77040 (Fairbanks - Northwest Crossing area)
NA
----------------------------------------
Posting #16

State Farm


Data Analyst

Bloomington, IL 61702
NA
----------------------------------------
Posting #17

mlok consulting inc


Data Analyst
new
San Francisco, CA

$35 - $40 an hour
----------------------------------------
Posting #18

Pruitthealth


Data Analyst - Financial Analyst

Norcross, GA
NA
----------------------------------------
Posting #19

Leonardo DRS


Data Management Analyst

St. Louis, MO 63121
NA
----------------------------------------
********************Success!!********************

/Users/beastmode/opt/anaconda3/lib/python3.7/site-packages/splinter/driver/webdriver/__init__.py:528: FutureWarning: browser.find_link_by_partial_text is deprecated. Use browser.links.find_by_partial_text instead.
  FutureWarning,

Page: 2
--------------------------------------------------------------------------------
Posting #20

Sourceability


Business Intelligence Analyst/Data Analyst

Irvine, CA 92618 (Irvine Health and Science Complex area)
NA
----------------------------------------
Posting #21

Private


Data Analyst

St. Louis, MO 63123

$13 an hour
----------------------------------------
Posting #22

The Brixton Group


Sr. Data Analyst

Huntersville, NC 28078

$100,000 - $135,000 a year
----------------------------------------
Posting #23

Confidential


Data Analyst

Santa Ana, CA
NA
----------------------------------------
Posting #24

Bellwether Staffing Solutions


Audit Data Analyst

White Plains, NY

$85,000 - $90,000 a year
----------------------------------------
Posting #25

Oneida Nation Enterprises


Business Analyst - Transformation

Verona, NY 13478

$40,000 - $80,000 a year
----------------------------------------
Posting #26

Comprehensive Health Serv


Data Analyst

Reston, VA 20190
NA
----------------------------------------
Posting #27

Showwcase


Data Analyst Intern

San Francisco, CA

$16 an hour
----------------------------------------
Posting #28

Santanna Energy Services


Junior Data Analyst
new
Austin, TX 78729
NA
----------------------------------------
Posting #29

Verde Natural


Data Analyst

Denver, CO 80216 (Northeast Park Hill area)
NA
----------------------------------------
Posting #30

LabYakk


Data Science Intern
new
San Francisco Bay Area, CA

$19 - $21 an hour
----------------------------------------
Posting #31

Indiana State Department of Health


Epidemiology Data Analyst (Contract)

Indianapolis, IN 46204 (Downtown area)

$21 an hour
----------------------------------------
Posting #32

Cobbs Creek Healthcare


Entry Level Data Analyst - Summer 2020

Newtown Square, PA 19073
NA
----------------------------------------
Posting #33

Entera


Product and Data Analyst

Houston, TX
NA
----------------------------------------
Posting #34

Reynolds and Reynolds


Data Analyst

Houston, TX 77040 (Fairbanks - Northwest Crossing area)
NA
----------------------------------------
Posting #35

State Farm


Data Analyst

Bloomington, IL 61702
NA
----------------------------------------
Posting #36

mlok consulting inc


Data Analyst
new
San Francisco, CA

$35 - $40 an hour
----------------------------------------
Posting #37

Pruitthealth


Data Analyst - Financial Analyst

Norcross, GA
NA
----------------------------------------
Posting #38

Leonardo DRS


Data Management Analyst

St. Louis, MO 63121
NA
----------------------------------------
********************Success!!********************
Page: 3
--------------------------------------------------------------------------------
Posting #39

Exceptional Lives https://exceptionallives.org


Data Analytics/Digital Marketing Analyst

Boston, MA 02109 (Downtown area)

$70,000 - $90,000 a year
----------------------------------------
Posting #40

Brook Valley Management


Retail Data Analyst

Meadowbrook, AL 35242

$60,000 - $75,000 a year
----------------------------------------
Posting #41

Southern Management Corporation


Credit Data Business Analyst

Greenville, SC 29601
NA
----------------------------------------
Posting #42

Datamatics Global Services Inc


Quality Analyst \ Data Analyst - Medical Devices

Des Plaines, IL 60018

$38.00 - $38.25 an hour
----------------------------------------
Posting #43

CDK Global


BI Data Analyst Reporting Lead

San Jose, CA 95134 (North San Jose area)
NA
----------------------------------------
Posting #44

Green Bay Packers


Football Data Analyst

Green Bay, WI
NA
----------------------------------------
Posting #45

Microsolutiontek


Entry Level Business Analyst

Houston, TX

$64,000 - $74,000 a year
----------------------------------------
Posting #46

Green Bay Packers, Inc.


Football Data Analyst

Green Bay, WI 54304
NA
----------------------------------------
Posting #47

TEKEDGE SOLUTION, INC.


Data Analyst

Dallas, TX 75201 (City Center District area)

$65,000 - $80,000 a year
----------------------------------------
Posting #48

Congruity360


Data Analyst
new
Norwell, MA 02061

$50,000 - $80,000 a year
----------------------------------------
Posting #49

Veteran Affairs


Health Sciences Research Data Programmer/Analyst

Seattle, WA 98108 (North Beacon Hill area)

$81,404 - $92,155 a year
----------------------------------------
Posting #50

Ohm Systems Inc


Data Reporting Analyst
new
Dallas, TX
NA
----------------------------------------
Posting #51

Colony Brands, Inc.


Data Analyst
new
Monroe, WI
NA
----------------------------------------
Posting #52

Quantum Technologies Inc.


Entry Level Data Analyst

Falls Church, VA 22043

$50,000 - $80,000 a year
----------------------------------------
Posting #53

BrightBytes


Data Analyst (Atlanta)

Atlanta, GA 30326 (Buckhead area)
NA
----------------------------------------
Posting #54

Shelter Insurance


Data Analyst - Underwriting

Columbia, MO

$43,735 - $63,677 a year
----------------------------------------
Posting #55

Confidential - E-Commerce Agency


E-Commerce Business Analyst

Woodbridge, CT 06525

$85,000 - $120,000 a year
----------------------------------------
********************Success!!********************
Page: 4
--------------------------------------------------------------------------------
Posting #56

Exceptional Lives https://exceptionallives.org


Data Analytics/Digital Marketing Analyst

Boston, MA 02109 (Downtown area)

$70,000 - $90,000 a year
----------------------------------------
Posting #57

Brook Valley Management


Retail Data Analyst

Meadowbrook, AL 35242

$60,000 - $75,000 a year
----------------------------------------
Posting #58

Southern Management Corporation


Credit Data Business Analyst

Greenville, SC 29601
NA
----------------------------------------
Posting #59

Datamatics Global Services Inc


Quality Analyst \ Data Analyst - Medical Devices

Des Plaines, IL 60018

$38.00 - $38.25 an hour
----------------------------------------
Posting #60

CDK Global


BI Data Analyst Reporting Lead

San Jose, CA 95134 (North San Jose area)
NA
----------------------------------------
Posting #61

Green Bay Packers


Football Data Analyst

Green Bay, WI
NA
----------------------------------------
Posting #62

Microsolutiontek


Entry Level Business Analyst

Houston, TX

$64,000 - $74,000 a year
----------------------------------------
Posting #63

Green Bay Packers, Inc.


Football Data Analyst

Green Bay, WI 54304
NA
----------------------------------------
Posting #64

TEKEDGE SOLUTION, INC.


Data Analyst

Dallas, TX 75201 (City Center District area)

$65,000 - $80,000 a year
----------------------------------------
Posting #65

Congruity360


Data Analyst
new
Norwell, MA 02061

$50,000 - $80,000 a year
----------------------------------------
Posting #66

Veteran Affairs


Health Sciences Research Data Programmer/Analyst

Seattle, WA 98108 (North Beacon Hill area)

$81,404 - $92,155 a year
----------------------------------------
Posting #67

Ohm Systems Inc


Data Reporting Analyst
new
Dallas, TX
NA
----------------------------------------
Posting #68

Colony Brands, Inc.


Data Analyst
new
Monroe, WI
NA
----------------------------------------
Posting #69

Quantum Technologies Inc.


Entry Level Data Analyst

Falls Church, VA 22043

$50,000 - $80,000 a year
----------------------------------------
Posting #70

BrightBytes


Data Analyst (Atlanta)

Atlanta, GA 30326 (Buckhead area)
NA
----------------------------------------
Posting #71

Shelter Insurance


Data Analyst - Underwriting

Columbia, MO

$43,735 - $63,677 a year
----------------------------------------
Posting #72

Confidential - E-Commerce Agency


E-Commerce Business Analyst

Woodbridge, CT 06525

$85,000 - $120,000 a year
----------------------------------------
********************Success!!********************
Page: 5
--------------------------------------------------------------------------------
Posting #73

AmeriWound, LLC


Data Analyst
new
Mayfield Heights, OH 44124

$23 - $28 an hour
----------------------------------------
Posting #74

Smithfield Foods


Finance Data Analytics Analyst

Smithfield, VA 23430
NA
----------------------------------------
Posting #75

Dovenmuehle


Data Integration Analyst l - Transfer & Conversions/Flow

Elgin, IL 60120
NA
----------------------------------------
Posting #76

The Brixton Group


Data Analyst

Huntersville, NC 28078
NA
----------------------------------------
Posting #77

Contact 1


Data Analyst (Federal Contract)

Washington, DC

$30 - $40 an hour
----------------------------------------
Posting #78

Sandstone Medical Solutions


Data Analyst

Las Vegas, NV 89128 (Desert Shores area)

$20 - $25 an hour
----------------------------------------
Posting #79

Sunnyvale Community Services


Data Quality Analyst

Sunnyvale, CA 94086 (East Murphy area)

$25 - $33 an hour
----------------------------------------
Posting #80

Horizonsoftech


Data Analyst

McLean, VA

$55,000 - $65,000 a year
----------------------------------------
Posting #81

MobilityWare


Data Analyst, Monetization
new
Irvine, CA 92602 (Lower Peters Canyon area)
NA
----------------------------------------
Posting #82

DTSV


Data Analyst
new
Winchester, VA
NA
----------------------------------------
Posting #83

Sev1Tech, LLC


Data Analyst

United States
NA
----------------------------------------
Posting #84

MilliporeSigma


Data Science Intern

Rockville, MD 20850

$20 - $25 an hour
----------------------------------------
Posting #85

Center for Global Development


Research Assistant - Global Health Data Analysis

Washington, DC 20036 (Downtown area)
NA
----------------------------------------
Posting #86

MediaMelon


Data Scientist Intern

San Francisco, CA 94133 (Russian Hill area)
NA
----------------------------------------
Posting #87

Mr. Cooper


Data Analyst - Dialer Analytics

Lewisville, TX 75067

$18 - $27 an hour
----------------------------------------
Posting #88

Confidential Medical Device Retailer


Sales Analyst with Excellent Excel Skills - Must LOVE DATA

Waco, TX

$40,000 - $55,000 a year
----------------------------------------
Posting #89

New York City Department of Correction


Director of Data Analytics and Research

Queens, NY

$90,000 - $105,000 a year
----------------------------------------
Posting #90

Liberty Mutual Insurance


Data Analyst
new
Indianapolis, IN 46201

$76,900 - $108,000 a year
----------------------------------------

********************Success!!********************
Page: 6
--------------------------------------------------------------------------------
Posting #91

Secure Collateral Management


Data Analyst Associate

Dallas, TX 75228 (Northeast Dallas area)

$12 - $28 an hour
----------------------------------------
Posting #92

Kawahara Nurseries


IT Business Analyst

Morgan Hill, CA 95037
NA
----------------------------------------
Posting #93

EPS Inc.


HUD Subsidized Housing Data Analyst/Processor

South Burlington, VT 05403

$35,000 - $40,000 a year
----------------------------------------
Posting #94

Axia


Senior Healthcare Data Analyst

Jacksonville, FL 32246 (Windy Hill area)
NA
----------------------------------------
Posting #95

RePublic Schools


Data and Assessment Analyst

Nashville, TN 37209

$48,682 - $60,000 a year
----------------------------------------
Posting #96

Tilde Staff Inc.


Data Analyst

Pasadena, CA
NA
----------------------------------------
Posting #97

4 Mile Analytics


Data Analyst (Remote, USA, Full-Time)

Remote
NA
----------------------------------------
Posting #98

Harbor Freight Tools USA, Inc.


Jr Data/Reporting Analyst

Calabasas, CA 91302

$32 - $39 an hour
----------------------------------------
Posting #99

ASAP Solutions Group, LLC


Data Analyst - Non Profit

Atlanta, GA 30308 (Old Fourth Ward area)

$35 - $40 an hour
----------------------------------------
Posting #100

Palm Beach Accountable Care Organization, LLC


SQL Data Analyst

Palm Springs, FL 33406
NA
----------------------------------------
Posting #101

Nasscomm


Data Analyst (Financial & Business intelligence)

Fort Collins, CO

$28 - $30 an hour
----------------------------------------
Posting #102

EAG Services


Data Analyst - Report Writer

Houston, TX 77002 (Downtown area)
NA
----------------------------------------
Posting #103

Amivero


Junior Data Analyst

Washington, DC

$65,000 - $70,000 a year
----------------------------------------
Posting #104

Locus Biosciences


Data Analyst

Research Triangle Park, NC
NA
----------------------------------------
Posting #105

Brooksource


Jr. Data Analyst

Phoenix, AZ 85012 (Alhambra area)

$60,000 - $75,000 a year
----------------------------------------
Posting #106

Onebridge


Data Analyst

Indianapolis, IN 46256 (Fall Creek area)
NA
----------------------------------------
Posting #107

Eagle Technologies, Inc.


Data/Research Analyst

Arlington, VA
NA
----------------------------------------
********************Success!!********************
Page: 7
--------------------------------------------------------------------------------
Posting #108

Talent Network Solutions LLC


Data Analyst

Hartford, CT

$35 - $50 an hour
----------------------------------------
Posting #109

The Health Collaborative


Data Analyst I

Cincinnati, OH 45202 (Mt. Auburn area)

$60,000 - $66,000 a year
----------------------------------------
Posting #110

Signify Health


Data Quality Analyst

Dallas, TX
NA
----------------------------------------
Posting #111

ProFocus


Data Analyst - 0369

Beaverton, OR 97005 (Central Beaverton area)
NA
----------------------------------------
Posting #112

TechnologyAdvice


Data Analyst

Nashville, TN 37211
NA
----------------------------------------
Posting #113

Dataspace


077: Data Science Analyst

Detroit, MI
NA
----------------------------------------
Posting #114

Washington University in St. Louis


Statistical Data Analyst - Genetics

St. Louis, MO 63130

$47,986 - $61,194 a year
----------------------------------------
Posting #115

KKI Capital


Quantitative/Data Analyst Intern

New York, NY
NA
----------------------------------------
Posting #116

Aptive


Data Analyst

Washington, DC
NA
----------------------------------------
Posting #117

Eaton


Eaton Intern - Data Analyst (Eden Prairie, MN)

Eden Prairie, MN
NA
----------------------------------------
Posting #118

Celink


Business Analyst

Austin, TX
NA
----------------------------------------
Posting #119

Envision LLC


Data Analyst

St. Louis, MO 63127
NA
----------------------------------------
Posting #120

OpTech LLC


Healthcare Data Analyst

Detroit, MI
NA
----------------------------------------
Posting #121

Ardent Eagle Solutions


Data Analyst (Researcher)

Washington, DC
NA
----------------------------------------
Posting #122

Polk County Board of County Commissioners


Logistics Data Analyst

Winter Haven, FL 33880

$43,366 - $66,331 a year
----------------------------------------
Posting #123

First Notch Technology


Data Analyst with sql

Richmond, VA

$22 an hour
----------------------------------------
Posting #124

Dominion National


Data and Reporting Analyst

Arlington, VA 22202 (Aurora Highlands area)
NA
----------------------------------------
Posting #125

Church Pension Group Services Corporation


Assistant Business and Data Analyst (Excel Professional)

New York, NY
NA
----------------------------------------
********************Success!!********************
Page: 8
--------------------------------------------------------------------------------
Posting #126

Deacom, Inc.


Data Specialist

King of Prussia, PA

$60,000 - $95,000 a year
----------------------------------------
Posting #127

Gearbox Software


Data Analyst

Frisco, TX 75034
NA
----------------------------------------
Posting #128

Atlanta Public Schools


Junior Data Analyst

Atlanta, GA 30303 (Downtown area)

$20 an hour
----------------------------------------
Posting #129

InnovaCare Health - MMM of Florida


Healthcare Data Analyst

Miami, FL
NA
----------------------------------------
Posting #130

Maschmeyer Concrete Company of Florida


Data Analyst

Lake Park, FL 33403
NA
----------------------------------------
Posting #131

Anyone Home


Data Analyst

Lake Forest, CA 92630
NA
----------------------------------------
Posting #132

Onstream Pipeline Inspection Services Inc.


Data Analyst (Pipeline Inspection)

Houston, TX
NA
----------------------------------------
Posting #133

Ramsey Solutions


Data Analyst

Remote
NA
----------------------------------------
Posting #134

MarLabs


Data Analyst -Forensic

Houston, TX

$100,000 - $130,000 a year
----------------------------------------
Posting #135

Red Berry Innovations


Data Science Intern

Springfield, NE 68059

$15 - $25 an hour
----------------------------------------
Posting #136

Brooksource


Jr. Data Analyst

Berkeley, MO
NA
----------------------------------------
Posting #137

Real T Solutions


Data Entry Analyst

Las Vegas, NV 89102 (Rancho Charleston area)

$9 - $10 an hour
----------------------------------------
Posting #138

GEICO


Technical Business & Data Analyst

Chevy Chase, MD
NA
----------------------------------------
Posting #139

Integrated Services of Kalamazoo


Data Analyst

Kalamazoo, MI 49001
NA
----------------------------------------
Posting #140

First Notch Technology


Jr. Business Analyst

Nyack, NY

$50,000 - $60,000 a year
----------------------------------------
Posting #141

Envision LLC


Data Analyst -Intermediate

St. Louis, MO 63141
NA
----------------------------------------
********************Success!!********************
Page: 9
--------------------------------------------------------------------------------
Posting #142

Vitalus Health LLC


Data Analyst with Business Intelligence

Houston, TX 77019 (River Oaks area)
NA
----------------------------------------
Posting #143

Incedo


Business Data Analyst
new
Boston, MA

$90,000 - $100,000 a year
----------------------------------------
Posting #144

MedPharm


Data Analyst
new
Durham, NC 27703
NA
----------------------------------------
Posting #145

Abnormal Security


Junior Data Analyst

Lehi, UT
NA
----------------------------------------
Posting #146

CenturyLink


Data Analyst-(Remote)

Broomfield, CO 80021 (Interlocken area)
NA
----------------------------------------
Posting #147

Community Services Employment Training, Inc


Data Analyst

Visalia, CA

$19.64 - $26.79 an hour
----------------------------------------
Posting #148

Cloudbigdata Technologies


Entry Level Data Analyst

Foster City, CA
NA
----------------------------------------
Posting #149

HITRECORD


Data Analyst

Los Angeles, CA
NA
----------------------------------------
Posting #150

Reddaiah, Inc


Data Scientist / Data Base Analyst

Atlanta, GA 30301 (Buckhead area)

$40 - $50 an hour
----------------------------------------
Posting #151

Harris Health System


Patient Satisfaction Data Analyst - Ben Taub Hospital

Houston, TX 77030 (Medical area)
NA
----------------------------------------
Posting #152

Harborview Health Systems - Corporate Office


Revenue Analyst

Blackshear, GA
NA
----------------------------------------
Posting #153

Adil Business Systems, Inc.


Data Analyst

Charlotte, NC 28204 (Elizabeth area)

$35 - $40 an hour
----------------------------------------
Posting #154

Cambay Consulting LLC


Business Analyst/Data Analyst
new
New York, NY
NA
----------------------------------------
Posting #155

LINDT & SPRUNGLI


Insights & Data Analyst

Stratham, NH
NA
----------------------------------------
Posting #156

ClearOne Advantage


Agile Scrum Coach / Leader & Business Analyst

Baltimore, MD 21224 (Canton Industrial Area area)
NA
----------------------------------------
Posting #157

Vera Whole Health


Sr. Data Analyst

Seattle, WA 98104 (International District area)
NA
----------------------------------------
Posting #158

Chevo Consulting


Data Management Analyst

Washington, DC
NA
----------------------------------------

********************Success!!********************